# Travis CI Configuration File

# Use new Travis container-based infrastructure
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

dist: trusty

# Tell Travis CI we're using PHP
language: php

# Configure caches
cache:
  apt: true
  directories:
    - node_modules
    - vendor
    - $HOME/.composer/cache

php:
  - 7.3
  - 7.2
  - 7.1
  - 7.0
  - 5.6

env:
  global:
    - WPF2BR_TRAVISCI=travis:phpunit
  matrix:
    - WP_VERSION=trunk
    - WP_VERSION=5.2
    - WP_VERSION=5.1
    - WP_VERSION=5.0
    - WP_VERSION=4.9
    - WP_VERSION=4.8
    - WP_VERSION=4.7

matrix:
  fast_finish: true
  include:
    - php: 5.3
      env: WP_VERSION=trunk
      dist: precise
    - php: 5.3
      env: WP_VERSION=5.2
      dist: precise
    - php: 5.3
      env: WP_VERSION=5.1
      dist: precise
    - php: 5.3
      env: WP_VERSION=5.0
      dist: precise
    - php: 5.3
      env: WP_VERSION=4.9
      dist: precise
    - php: 5.3
      env: WP_VERSION=4.8
      dist: precise
    - php: 5.3
      env: WP_VERSION=4.7
      dist: precise
    - php: 7.1
      env: WP_VERSION=trunk WPF2BR_TRAVISCI=travis:codecoverage
    - php: nightly
      env: WP_VERSION=trunk
  exclude:
    - php: 7.3
      env: WP_VERSION=4.8
    - php: 7.3
      env: WP_VERSION=4.7
    - php: 7.2
      env: WP_VERSION=4.8
    - php: 7.2
      env: WP_VERSION=4.7
  allow_failures:
    - php: nightly
    - env: WP_VERSION=trunk WPF2BR_TRAVISCI=travis:codecoverage

# Clones WordPress and configures our testing environment.
before_script:
  - |
    # Remove Xdebug for a huge performance increase, but not from nightly:
    if [[ "$WPF2BR_TRAVISCI" != "travis:codecoverage" && -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]]; then
      phpenv config-rm xdebug.ini
    else
      echo "We are running codecoverage or xdebug.ini does not exist"
    fi
  - |
    # Export Composer's global bin dir to PATH, but not on PHP 5.2:
    if [[ ${TRAVIS_PHP_VERSION:0:3} != "5.2" ]]; then
      composer config --list --global
      export PATH=`composer config --list --global | grep '\[home\]' | { read a; echo "${a#* }/vendor/bin:$PATH"; }`
    fi
  - |
    # Install the specified version of PHPUnit depending on the PHP version:
    if [[ "$WPF2BR_TRAVISCI" == "travis:phpunit" || "$WPF2BR_TRAVISCI" == "travis:codecoverage" ]]; then
      case "$TRAVIS_PHP_VERSION" in
        7.3|7.2|7.1|7.0|nightly)
          echo "Using PHPUnit 6.x"
          travis_retry composer global require "phpunit/phpunit:^6"
          ;;
        5.6|5.5|5.4|5.3)
          echo "Using PHPUnit 4.x"
          travis_retry composer global require "phpunit/phpunit:^4"
          ;;
        *)
          echo "No PHPUnit version handling for PHP version $TRAVIS_PHP_VERSION"
          exit 1
          ;;
      esac
    fi
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - npm --version
  - node --version
  - nvm install 10.13.0
  - npm install -g grunt-cli
  - npm install
  - npm prune
  - mysql --version
  - phpenv versions
  - php --version
  - php -m
  - npm --version
  - node --version
  - which phpunit
  - phpunit --version
  - curl --version
  - grunt --version
  - git --version
  - svn --version

script: grunt $WPF2BR_TRAVISCI

after_script:
  - |
    if [[ "$WPF2BR_TRAVISCI" == "travis:codecoverage" ]] ; then
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi
